repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
            -   id: check-added-large-files
            -   id: mixed-line-ending
            -   id: check-shebang-scripts-are-executable
            -   id: end-of-file-fixer
            -   id: trailing-whitespace
