const val KotlinJVMPlugin = "org.jetbrains.kotlin.jvm"
const val KotlinMultiplatformPlugin = "org.jetbrains.kotlin.multiplatform"
const val KotlinXSerialization = "org.jetbrains.kotlin.plugin.serialization"
const val ShadowJar = "com.github.johnrengelman.shadow"
const val KotlinJvm = "jvm"
