object Versions {
    val kotlinXDateTime = "0.4.0"
    val ktorVersion = "2.1.0"
    val kotlinVersion = "1.8.0-Beta"
    val logbackVersion = "1.2.11"
    val exposedVersion = "0.39.2"
    val arrowVersion = "1.1.3-rc.1"
    val arrowSuspendApp = "0.3.0"
    val assertKVersion = "0.25"
    val coroutinesVersion = "1.6.4"
    val keycloakVersion = "19.0.1"
    val okHttpVersion = "4.10.0"
    val flywayVersion = "8.0.1"
    val moshiVersion = "1.12.0"
    val kotlinXSerializationVersion = "1.4.0"
    val mockkVersion = "1.12.7"
    val jacksonDataformatXMLVersion = "2.13.4"
    val luceneCoreVersion = "9.4.1"
    val shadowJarVersion = "7.1.2"
    val koinVersion = "3.2.2"
    val caffeineVersion = "3.1.2"
    val dokkaVersion = "1.7.20"
}
