object Versions {
    const val kotlinXDateTime = "0.4.1"
    const val ktorVersion = "2.3.5"
    const val kotlinVersion = "1.9.10"
    const val logbackVersion = "1.4.11"
    const val exposedVersion = "0.44.0"
    const val arrowVersion = "1.2.0"
    const val arrowSuspendApp = "0.4.0"
    const val assertKVersion = "0.27.0"
    const val coroutinesVersion = "1.7.3"
    const val flywayVersion = "9.19.0"
    const val mockkVersion = "1.18.8"
    const val shadowJarVersion = "8.1.1"
    const val koinVersion = "3.5.0"
    const val caffeineVersion = "3.1.8"
    const val dokkaVersion = "1.9.0"
    const val detektVersion = "1.23.1"
    const val ktLintVersion = "11.6.0"
}
